name: Build CHelper-Doc

on:
  push:
    branches: [ "master", "dev" ]
    paths:
      - '.github/workflows/build-doc.yml'
      - 'CHelper-Doc/**'
  pull_request:
    branches: [ "master", "dev" ]
    paths:
      - '.github/workflows/build-doc.yml'
      - 'CHelper-Doc/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: latest

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'
          cache-dependency-path: 'CHelper-Doc/pnpm-lock.yaml'

      - name: Install dependencies
        working-directory: ${{ github.workspace }}/CHelper-Doc
        run: pnpm install

      - name: Build
        working-directory: ${{ github.workspace }}/CHelper-Doc
        run: npx vitepress build --base=/chelper_doc/
