name: Android CI

on:
  push:
    branches: ["master", "dev"]
    paths:
      - ".github/workflows/build-android.yml"
      - "CHelper-Android/**"
  pull_request:
    branches: ["master", "dev"]
    paths:
      - ".github/workflows/build-android.yml"
      - "CHelper-Android/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK 27
        uses: actions/setup-java@v6
        with:
          java-version: "27"
          distribution: "temurin"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Grant execute permission for gradlew
        working-directory: ${{ github.workspace }}/CHelper-Android
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: ${{ github.workspace }}/CHelper-Android
        run: ./gradlew build
