name: Build CHelper-Doc

on:
  push:
    branches: ["master", "dev"]
    paths:
      - ".github/workflows/build-doc.yml"
      - "CHelper-Doc/**"
      - ".node-version"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
  pull_request:
    branches: ["master", "dev"]
    paths:
      - ".github/workflows/build-doc.yml"
      - "CHelper-Doc/**"
      - ".node-version"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Set up Node
        uses: actions/setup-node@v7
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        working-directory: ${{ github.workspace }}/CHelper-Doc
        run: pnpm exec vitepress build --base=/chelper_doc/
